name: CD

on:
  push:
    branches:
      - master
  release:
    types:
      - created

env:
  BUILD_TYPE: Release

jobs:
  cancel_previous_runs:
    runs-on: ubuntu-latest
    name: Cancel Previous Runs
    steps:
    - uses: styfle/cancel-workflow-action@0.10.0
      with:
        access_token: ${{ github.token }}

  test_ubuntu:
    needs: [cancel_previous_runs]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  build_release_macos:
    needs: [test_ubuntu] #, test_windows, test_macos]
    name: Build Release macOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
    #- name: Sign Build
    #  run: .github/scripts/sign-macos.sh
    #  env:
    #    MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
    #    MACOS_CERTIFICATE_P12: ${{ secrets.MACOS_CERTIFICATE_P12 }}
    #    MACOS_APPSTORE_APP_PASSWORD: ${{ secrets.MACOS_APPSTORE_APP_PASSWORD }}
    #    MACOS_APPSTORE_USERNAME: ${{ secrets.MACOS_APPSTORE_USERNAME }}
    #    MACOS_DEVELOPER_ID: ${{ secrets.MACOS_DEVELOPER_ID }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos
        path: build/bin/Qucs-S.dmg
